### PR TITLE
Checkbox + Radio flag for ellipsis label

### PR DESCRIPTION
**Pull request by marcin-zapala**
wrap to next line for radio and checkbox
image

this is prepared only for this defect

### CODE REVIEW

**Comment by renaudtertrais** [comment]
@aleksandranovakovic can you validate the word break (end of line) ?

**Comment by aleksandranovakovic** [comment]
Works for me

**Comment by marcin-zapala** [comment]
@aleksandranovakovic updated

**Comment by aleksandranovakovic** [comment]
Cool, thanks

**Pull request merged**
